### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by grgbibek** [baralmanish/PushDataToUrl#1]
In the example index page. Need to change : <script type="text/javascript" src="../lib/pushToUrl.jQuery.js"></script> to
<script type="text/javascript" src="../src/pushToUrl.jQuery.js"></script>.
Change lib to src for running example properly.

**Comment by baralmanish** [comment]
Please follow the following commands:

1. `npm install`
2. `npm run build` or `npm run prepublish`
Babel will transpile ES6 => ES5 and minify the code. and publish the compiled code in `/lib/pushToUrl.jQuery.js`
